"""add

Revision ID: 72d13f93eedf
Revises: b2ddf4614512
Create Date: 2026-10-09 18:26:50.733627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d13f93eedf'
down_revision: Union[str, Sequence[str], None] = 'b2ddf4614512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id_created_at', 'posts', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id_created_at', table_name='posts')
    # ### end Alembic commands ###
