"""fix guid type

Revision ID: b2ddf4614512
Revises: e3b51f390a1d
Create Date: 2026-10-07 19:43:01.168869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2ddf4614512'
down_revision: Union[str, Sequence[str], None] = 'e3b51f390a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'id',
               existing_type=mysql.CHAR(length=32),
               type_=fastapi_users_db_sqlalchemy.generics.GUID(),
               existing_nullable=False)
    op.alter_column('posts', 'user_id',
               existing_type=mysql.CHAR(length=32),
               type_=fastapi_users_db_sqlalchemy.generics.GUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=fastapi_users_db_sqlalchemy.generics.GUID(),
               type_=mysql.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('posts', 'id',
               existing_type=fastapi_users_db_sqlalchemy.generics.GUID(),
               type_=mysql.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
